// Generated by scripts/build-city-maps.mjs — do not edit.
export const CITY_MAP_IDS: readonly string[] = ["abha","abu-dhabi","alula","barcelona","cairo","dubai","edinburgh","istanbul","jeddah","khobar","london","los-angeles","madinah","makkah","new-york","paris","riyadh","rome","san-francisco","tokyo","washington"];
