/**
 * Which streets, districts and extra places to fetch for each city map.
 *
 * Landmarks, cafés and restaurants come from the city guides in
 * src/data/countries.ts automatically; only the extras live here.
 * Every name is geocoded against OpenStreetMap — anything that cannot be
 * found inside the city's box is dropped, never guessed.
 */

/** @typedef {{ roads?: string[], districts?: string[], hotel?: string[], tower?: string[], office?: string[], mall?: string[], radius?: number, aliases?: Record<string, string[]> }} CityExtras */

/** @type {Record<string, CityExtras>} */
export const CITY_EXTRAS = {
  riyadh: {
    radius: 0.32,
    aliases: {
      'Kingdom Centre Tower': ['Kingdom Centre'],
      'Masmak Fortress': ['Masmak'],
      'Al Faisaliah Tower': ['برج الفيصلية'],
      Brew92: ['Brew 92'],
      'The Ritz-Carlton Riyadh': ['ريتز كارلتون'],
      'Fairmont Riyadh': ['فيرمونت الرياض'],
      'Four Seasons Hotel Riyadh': ['Four Seasons Hotel'],
      'King Fahd Road': ['طريق الملك فهد'],
      'Olaya Street': ['شارع العليا', 'Olaya Road'],
      'Prince Mohammed bin Abdulaziz Road': ['شارع التحلية', 'Prince Mohammed Bin Abdul Aziz Road'],
      'King Abdullah Road': ['طريق الملك عبدالله'],
      'Makkah Al Mukarramah Road': ['طريق مكة المكرمة'],
      'Northern Ring Road': ['الطريق الدائري الشمالي'],
      'Eastern Ring Road': ['الطريق الدائري الشرقي'],
      'King Khalid Road': ['طريق الملك خالد'],
      'King Salman Road': ['طريق الملك سلمان'],
      'Al Urubah Road': ['طريق العروبة', 'Al Uaroba Road'],
      'Prince Turki bin Abdulaziz Al Awwal Road': ['طريق الأمير تركي بن عبدالعزيز الأول'],
      'Takhassusi Street': ['شارع التخصصي', 'Al Takhassusi'],
      'Al Malqa': ['الملقا'],
      'Al Olaya': ['العليا'],
      'As Sulimaniyah': ['السليمانية'],
      'An Nakheel': ['النخيل'],
      'Al Batha': ['البطحاء'],
    },
    roads: [
      'King Fahd Road',
      'Olaya Street',
      'Prince Mohammed bin Abdulaziz Road',
      'King Abdullah Road',
      'Makkah Al Mukarramah Road',
      'Northern Ring Road',
      'Eastern Ring Road',
      'King Khalid Road',
      'King Salman Road',
      'Prince Turki bin Abdulaziz Al Awwal Road',
      'Al Urubah Road',
      'Takhassusi Street',
    ],
    districts: ['Al Olaya', 'Al Malqa', 'Al Murabba', 'As Sulimaniyah', 'Hittin', 'Al Wurud', 'An Nakheel', 'Al Batha', 'Al Yasmin'],
    hotel: [
      'The Ritz-Carlton Riyadh',
      'Four Seasons Hotel Riyadh',
      'Fairmont Riyadh',
      'Burj Rafal Hotel Kempinski',
      'Hilton Riyadh Hotel & Residences',
      'Bab Samhan',
    ],
    tower: ['Kingdom Centre', 'Al Faisaliah Tower', 'PIF Tower', 'Riyadh TV Tower', 'Burj Rafal', 'Al Majdoul Tower'],
    office: ['King Abdullah Financial District', 'Ministry of Foreign Affairs'],
    mall: ['Riyadh Park', 'Kingdom Centre Mall', 'Al Nakheel Mall', 'Riyadh Gallery Mall', 'Panorama Mall', 'Granada Mall'],
  },
  jeddah: {
    radius: 0.3,
    aliases: {
      'Al-Balad (Historic Jeddah)': ['Historic Jeddah', 'جدة التاريخية'],
      'Prince Majed Road': ['Prince Majid Road'],
    },
    roads: ['King Abdulaziz Road', 'Prince Sultan Road', 'Al Madinah Al Munawwarah Road', 'Palestine Street', 'Tahlia Street', 'King Fahd Road', 'Corniche Road', 'Prince Majed Road', 'Al Andalus Road'],
    districts: ['Al-Balad', 'Al Hamra', 'Ash Shati', 'Al Rawdah', 'Al Zahra', 'Obhur'],
    hotel: ['The Ritz-Carlton Jeddah', 'Park Hyatt Jeddah', 'Rosewood Jeddah', 'Waldorf Astoria Jeddah - Qasr Al Sharq', 'Shangri-La Jeddah'],
    tower: ['Jeddah Tower', 'National Commercial Bank Tower', 'King Road Tower'],
    office: ['Islamic Development Bank'],
    mall: ['Red Sea Mall', 'Mall of Arabia', 'Al Andalus Mall', 'Tahlia Mall'],
  },
  alula: {
    radius: 0.4,
    aliases: {
      'AlUla Old Town': ['Old Town'],
      'Habitas AlUla': ['Habitas'],
    },
    districts: [],
    hotel: ['Banyan Tree AlUla', 'Habitas AlUla', 'Shaden Resort'],
  },
  makkah: {
    radius: 0.12,
    roads: ['Ibrahim Al Khalil Road', 'Ajyad Street', 'King Abdulaziz Road', 'Umm Al Qura Road'],
    districts: ['Ajyad', 'Al Aziziyah', 'Mina', 'Arafat'],
    hotel: ['Fairmont Makkah Clock Royal Tower', 'Raffles Makkah Palace', 'Swissôtel Makkah', 'Hilton Makkah Convention Hotel'],
    tower: ['Abraj Al Bait'],
  },
  madinah: {
    radius: 0.15,
    roads: ['King Faisal Road', 'Quba Road', 'King Abdullah Road', 'Sultanah Road'],
    districts: ['Quba', 'Al Anbariyah', 'Uhud'],
    hotel: ['The Oberoi Madina', 'Anwar Al Madinah Mövenpick Hotel', 'Pullman Zamzam Madina'],
  },
  abha: {
    radius: 0.6,
    districts: ['Al Muftaha'],
    hotel: ['Abha Palace Hotel'],
  },
  khobar: {
    radius: 0.18,
    aliases: {
      'Sofitel Al Khobar The Corniche': ['Sofitel'],
    },
    roads: ['King Fahd Road', 'Prince Turki Street', 'King Abdullah Road', 'Corniche Road'],
    districts: ['Al Ulaya', 'Al Aqrabiyah', 'Al Rakah'],
    hotel: ['Sofitel Al Khobar The Corniche', 'Kempinski Hotel Al Khobar', 'Le Méridien Al Khobar'],
    mall: ['Al Rashid Mall'],
  },
  london: {
    radius: 0.12,
    roads: ['Oxford Street', 'Regent Street', 'Strand', 'Piccadilly', 'Whitehall', 'Victoria Embankment', 'Park Lane', 'Euston Road', 'Kensington Road'],
    districts: ['Westminster', 'Soho', 'Covent Garden', 'Mayfair', 'Kensington', 'Southwark', 'City of London', 'Camden Town'],
    hotel: ['The Savoy', 'The Ritz London', 'The Dorchester', 'Claridge’s', 'The Langham'],
    tower: ['The Shard', '30 St Mary Axe', 'One Canada Square', 'BT Tower'],
    office: ['Bank of England', '10 Downing Street'],
    mall: ['Harrods', 'Westfield London', 'Selfridges'],
  },
  'new-york': {
    radius: 0.12,
    roads: ['Broadway', 'Fifth Avenue', 'Park Avenue', 'Seventh Avenue', 'West 42nd Street', 'FDR Drive', 'Wall Street', 'Canal Street'],
    districts: ['Midtown', 'Harlem', 'Greenwich Village', 'SoHo', 'Financial District', 'Upper East Side', 'Upper West Side', 'Chinatown'],
    hotel: ['The Plaza', 'The Waldorf Astoria New York', 'The St. Regis New York', 'The Pierre'],
    tower: ['One World Trade Center', 'Chrysler Building', 'Rockefeller Center', 'Flatiron Building'],
    office: ['United Nations Headquarters', 'New York Stock Exchange'],
    mall: ['Macy’s Herald Square', 'The Shops at Columbus Circle'],
  },
  paris: {
    radius: 0.09,
    roads: ['Avenue des Champs-Élysées', 'Rue de Rivoli', 'Boulevard Saint-Germain', 'Boulevard Haussmann', 'Avenue de l’Opéra', 'Boulevard Saint-Michel', 'Quai d’Orsay'],
    districts: ['Le Marais', 'Montmartre', 'Saint-Germain-des-Prés', 'Quartier Latin', 'La Défense'],
    hotel: ['Hôtel Ritz Paris', 'Le Meurice', 'Hôtel Plaza Athénée', 'Le Bristol Paris', 'Shangri-La Paris'],
    tower: ['Tour Montparnasse'],
    office: ['Palais de l’Élysée'],
    mall: ['Galeries Lafayette Haussmann', 'Le Bon Marché'],
  },
  dubai: {
    radius: 0.2,
    roads: ['Sheikh Zayed Road', 'Al Khail Road', 'Jumeirah Beach Road', 'Al Wasl Road', 'Sheikh Mohammed bin Rashid Boulevard', 'Al Maktoum Road'],
    districts: ['Downtown Dubai', 'Dubai Marina', 'Jumeirah', 'Deira', 'Bur Dubai', 'Business Bay'],
    hotel: ['Burj Al Arab', 'Atlantis The Palm', 'Armani Hotel Dubai', 'Atlantis The Royal', 'One&Only Royal Mirage'],
    tower: ['Emirates Towers', 'Cayan Tower', 'Princess Tower', 'Dubai Frame'],
    office: ['Dubai International Financial Centre', 'Dubai World Trade Centre'],
    mall: ['The Dubai Mall', 'Mall of the Emirates', 'Dubai Marina Mall'],
  },
  istanbul: {
    radius: 0.12,
    roads: ['İstiklal Caddesi', 'Divanyolu Caddesi', 'Kennedy Caddesi', 'Barbaros Bulvarı', 'Ordu Caddesi'],
    districts: ['Sultanahmet', 'Beyoğlu', 'Kadıköy', 'Beşiktaş', 'Karaköy', 'Üsküdar'],
    hotel: ['Çırağan Palace Kempinski', 'Pera Palace Hotel', 'Four Seasons Hotel Istanbul at Sultanahmet'],
    tower: ['Maiden’s Tower', 'Istanbul Sapphire'],
    mall: ['İstinye Park'],
  },
  rome: {
    radius: 0.08,
    roads: ['Via del Corso', 'Via Nazionale', 'Via dei Fori Imperiali', 'Via Vittorio Veneto', 'Via della Conciliazione'],
    districts: ['Trastevere', 'Monti', 'Testaccio', 'Prati'],
    hotel: ['Hotel de Russie', 'Hotel Hassler Roma', 'Hotel Eden'],
    office: ['Palazzo del Quirinale'],
  },
  tokyo: {
    radius: 0.14,
    roads: ['Omotesando', 'Meiji-dori', 'Yasukuni-dori', 'Chuo-dori', 'Aoyama-dori', 'Sotobori-dori'],
    districts: ['Shinjuku', 'Shibuya', 'Ginza', 'Asakusa', 'Roppongi', 'Akihabara', 'Harajuku'],
    hotel: ['Imperial Hotel Tokyo', 'Park Hyatt Tokyo', 'The Peninsula Tokyo', 'Aman Tokyo'],
    tower: ['Tokyo Tower', 'Roppongi Hills Mori Tower', 'Tokyo Metropolitan Government Building'],
    office: ['National Diet Building'],
    mall: ['Ginza Six', 'Shibuya Scramble Square'],
  },
  cairo: {
    radius: 0.16,
    roads: ['Corniche El Nil', 'Tahrir Street', '26th of July Street', 'Al Azhar Street', 'Al Haram Street', 'Salah Salem Street'],
    districts: ['Zamalek', 'Downtown Cairo', 'Garden City', 'Islamic Cairo', 'Giza', 'Heliopolis'],
    hotel: ['Marriott Mena House', 'Four Seasons Hotel Cairo at Nile Plaza', 'Cairo Marriott Hotel'],
    tower: ['Cairo Tower'],
    office: ['Tahrir Square'],
  },
  barcelona: {
    radius: 0.08,
    roads: ['La Rambla', 'Passeig de Gràcia', 'Avinguda Diagonal', 'Gran Via de les Corts Catalanes', 'Via Laietana'],
    districts: ['Eixample', 'Gràcia', 'El Born', 'Barceloneta', 'El Raval'],
    hotel: ['Hotel Arts Barcelona', 'W Barcelona', 'Mandarin Oriental Barcelona'],
    tower: ['Torre Glòries'],
  },
  washington: {
    radius: 0.08,
    roads: ['Pennsylvania Avenue Northwest', 'Constitution Avenue Northwest', 'Independence Avenue Southwest', 'Massachusetts Avenue Northwest', 'K Street Northwest'],
    districts: ['Georgetown', 'Capitol Hill', 'Dupont Circle', 'Foggy Bottom'],
    hotel: ['The Willard InterContinental', 'The Hay-Adams'],
    tower: ['Washington Monument'],
    office: ['White House', 'United States Capitol', 'The Pentagon'],
  },
  'los-angeles': {
    radius: 0.2,
    roads: ['Hollywood Boulevard', 'Sunset Boulevard', 'Wilshire Boulevard', 'Santa Monica Boulevard', 'Rodeo Drive'],
    districts: ['Hollywood', 'Beverly Hills', 'Downtown Los Angeles', 'Santa Monica', 'Venice'],
    hotel: ['The Beverly Hills Hotel', 'Chateau Marmont'],
    tower: ['U.S. Bank Tower', 'Wilshire Grand Center'],
    mall: ['The Grove'],
  },
  'san-francisco': {
    radius: 0.08,
    roads: ['Market Street', 'Lombard Street', 'Van Ness Avenue', 'The Embarcadero', 'Geary Boulevard'],
    districts: ['Chinatown', 'Fisherman’s Wharf', 'Mission District', 'Haight-Ashbury', 'Nob Hill'],
    hotel: ['Fairmont San Francisco', 'The Palace Hotel'],
    tower: ['Salesforce Tower', 'Transamerica Pyramid', 'Coit Tower'],
  },
  edinburgh: {
    radius: 0.06,
    roads: ['Princes Street', 'High Street', 'George Street', 'Leith Walk', 'Lothian Road'],
    districts: ['Old Town', 'New Town', 'Leith', 'Stockbridge'],
    hotel: ['The Balmoral', 'The Caledonian'],
    office: ['Scottish Parliament Building'],
  },
  'abu-dhabi': {
    radius: 0.18,
    roads: ['Corniche Road', 'Sheikh Zayed bin Sultan Street', 'Hamdan bin Mohammed Street', 'Khalifa bin Zayed the First Street'],
    districts: ['Al Markaziyah', 'Saadiyat Island', 'Yas Island', 'Al Maryah Island'],
    hotel: ['Emirates Palace', 'The St. Regis Abu Dhabi', 'W Abu Dhabi - Yas Island'],
    tower: ['Etihad Towers', 'Aldar HQ'],
    office: ['Abu Dhabi Global Market'],
    mall: ['The Galleria Al Maryah Island', 'Yas Mall'],
  },
};
